name: "Setup Rust with Caching"
description: "Setup Rust toolchain with cargo caching"
inputs:
  target:
    description: "Rust target triple"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.target }}

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ inputs.target }}
