name: "Setup Cross Compilation"
description: "Setup cross-compilation for ARM64 Linux"
inputs:
  target:
    description: "Rust target triple"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup cross-compilation
      if: ${{ inputs.target == 'aarch64-unknown-linux-gnu' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
        echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
      shell: bash
