name: Lint

on:
  push:
    branches: [main]
  pull_request:
  workflow_call:

jobs:
  megalinter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7

      - name: megalinter
        uses: oxsecurity/megalinter@15e5b45552097e318c93de385779ce3b1084052c # v10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
