name: Pre-commit

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: biomejs/setup-biome@v2

      - uses: actions/setup-python@v6
        with:
          cache: pip
          python-version: 3.x

      - run: pip install -r requirements.txt

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - run: pre-commit run --all-files
